"""
ChecksumChecker
===============

Ben.Sanders@NHS.net

Checks the SHA1 checksum file generated by CertUtil against the hash
of the same file generated by the app.

This is as CertUtil doesn't have a simple check function (unlike
md5sum, for example), and we need to be able to confirm data transfer
integrity on Windows for our NGS run backups.

---------------

This is the main function, which loads the interface.

"""


from app.interface.interface import ChecksumChecker

if __name__ == "__main__":
    # This is a graphical tool only, it is not intended to be run from
    # the command line. So we just fire of the interface straight away.
    form = ChecksumChecker()
